#!/usr/bin/env python3
# Copyright (C) 2025 Keygraph, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3
# as published by the Free Software Foundation.
#
# Assemble (and verify) infra/sinas/sinas-package.yaml from the canonical
# per-resource fragments so there is exactly ONE source of truth for each
# artifact and the package can never drift from it.
#
#   python3 infra/sinas/assemble.py            # regenerate the package
#   python3 infra/sinas/assemble.py --check    # fail if it is stale (CI/runbook)
#
# Sources of truth (all committed, all independently verified):
#   functions/trigger_scan.py    functions/create_project.py   (py_compile)
#   connectors/engine.yaml       stores/projects.yaml          (yaml.safe_load)
# The finalizer model swap is applied as a PATCH (agents/finalizer.patch.yaml),
# NOT via the package, so it is not assembled here.
#
# No secrets are read or written; placeholders stay as `${{ vars.NAME }}`.

import argparse
import pathlib
import sys

import yaml

HERE = pathlib.Path(__file__).resolve().parent
PACKAGE = HERE / "sinas-package.yaml"

HEADER = (
    "# Copyright (C) 2025 Keygraph, Inc.\n"
    "#\n"
    "# This program is free software: you can redistribute it and/or modify\n"
    "# it under the terms of the GNU Affero General Public License version 3\n"
    "# as published by the Free Software Foundation.\n"
    "#\n"
    "# GENERATED by infra/sinas/assemble.py from the per-resource fragments.\n"
    "# Do NOT hand-edit the spec.functions[].code or the connector/store blocks;\n"
    "# edit the fragment under functions/, connectors/, or stores/ and re-run\n"
    "# `python3 infra/sinas/assemble.py`. Run with --check in CI to catch drift.\n"
    "#\n"
    "# Schema: native SinasPackage (apiVersion sinas.co/v1) per the\n"
    "# sinas-platform/skills `sinas-package-author` skill. See README.md for the\n"
    "# apply order, the via-12 component recreate-by-POST gotcha, and how the\n"
    "# install-time variables (ENGINE_BASE_URL, ENGINE_TRIGGER_TOKEN) are filled.\n"
    "#\n"
    "# Extensibility: spec.components is an explicit empty list. The sibling\n"
    "# component task appends report-view there (enabled_functions\n"
    "# [pentest/trigger_scan, pentest/create_project] + the four stores) and adds\n"
    "# its manifest entry under spec.manifests[0].requiredResources — no other\n"
    "# section changes.\n"
)


def func_body(path: pathlib.Path) -> str:
    """Return a function fragment's code with the AGPL/comment header removed."""
    lines = path.read_text().splitlines()
    start = next(i for i, line in enumerate(lines) if line.startswith("import "))
    return "\n".join(lines[start:]).rstrip() + "\n"


def load_fragment(path: pathlib.Path) -> dict:
    return yaml.safe_load(path.read_text())


def build() -> dict:
    connector = load_fragment(HERE / "connectors" / "engine.yaml")
    store = load_fragment(HERE / "stores" / "projects.yaml")

    functions = []
    fn_meta = {
        "trigger_scan": {
            "description": (
                "Start a scan on the engine, then mirror the engine-minted "
                "scanId into pentest/scans (T8). Deterministic, no LLM."
            ),
            "inputSchema": {
                "type": "object",
                "properties": {
                    "projectId": {"type": "string"},
                    "ref": {"type": "string"},
                },
                "required": ["projectId"],
            },
            "outputSchema": {
                "type": "object",
                "properties": {
                    "scanId": {"type": "string"},
                    "status": {"type": "string"},
                },
                "required": ["scanId", "status"],
            },
        },
        "create_project": {
            "description": (
                "Create a project on the engine (black-box or white-box), then "
                "mirror the engine-minted projectId into pentest/projects "
                "(T8/T9). No LLM."
            ),
            "inputSchema": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "targetUrl": {"type": "string"},
                    "mode": {"type": "string", "enum": ["blackbox", "whitebox"]},
                    "repoRef": {"type": "string"},
                },
                "required": ["name", "targetUrl", "mode"],
            },
            "outputSchema": {
                "type": "object",
                "properties": {"projectId": {"type": "string"}},
                "required": ["projectId"],
            },
        },
    }
    for name, meta in fn_meta.items():
        functions.append(
            {
                "namespace": "pentest",
                "name": name,
                "description": meta["description"],
                "sharedPool": True,
                "timeout": 30,
                "inputSchema": meta["inputSchema"],
                "outputSchema": meta["outputSchema"],
                "code": func_body(HERE / "functions" / f"{name}.py"),
            }
        )

    manifest = {
        "namespace": "pentest",
        "name": "aegis-pentest-integration",
        "description": "Manifest for the aegis two-way integration backend.",
        "requiredResources": [
            {"type": "store", "namespace": "pentest", "name": "projects"},
            {"type": "connector", "namespace": "pentest", "name": "engine"},
            {"type": "function", "namespace": "pentest", "name": "trigger_scan"},
            {"type": "function", "namespace": "pentest", "name": "create_project"},
            {"type": "agent", "namespace": "pentest", "name": "finalizer"},
            # TODO(sibling component task): append report-view here, e.g.
            # {"type": "component", "namespace": "pentest", "name": "report-view"},
        ],
        "requiredPermissions": [],
        "optionalPermissions": [],
        "exposedNamespaces": {},
        "storeDependencies": [],
    }

    return {
        "apiVersion": "sinas.co/v1",
        "kind": "SinasPackage",
        "package": {
            "name": "aegis-pentest-integration",
            "version": "0.1.0",
            "description": (
                "Two-way aegis<->Sinas backend: projects store, bearer engine "
                "connector, engine-minted trigger_scan / create_project "
                "functions."
            ),
            "author": "Aegis Team",
            "url": "https://github.com/keygraph/aegis",
        },
        "spec": {
            "variables": [
                {
                    "name": "ENGINE_BASE_URL",
                    "type": "text",
                    "description": (
                        "Public base URL of the hosted aegis-web control plane."
                    ),
                    "required": True,
                },
                {
                    "name": "ENGINE_TRIGGER_TOKEN",
                    "type": "secret",
                    "description": (
                        "Shared AEGIS_ENGINE_TRIGGER_TOKEN; Sinas->engine bearer "
                        "credential the engine connector carries. Write-only; "
                        "set once (T7)."
                    ),
                    "required": True,
                },
            ],
            "manifests": [manifest],
            "stores": [store],
            "connectors": [connector],
            "functions": functions,
            # Sibling component task appends report-view here (recreate-by-POST
            # on via-12). No other section changes.
            "components": [],
        },
    }


def render(doc: dict) -> str:
    body = yaml.safe_dump(doc, sort_keys=False, default_flow_style=False, width=88)
    return HEADER + "\n" + body


def main() -> int:
    ap = argparse.ArgumentParser(description="Assemble the SinasPackage.")
    ap.add_argument(
        "--check",
        action="store_true",
        help="Verify the committed package matches the fragments; non-zero if stale.",
    )
    args = ap.parse_args()

    rendered = render(build())

    if args.check:
        current = PACKAGE.read_text() if PACKAGE.exists() else ""
        if current != rendered:
            sys.stderr.write(
                "sinas-package.yaml is STALE — run `python3 "
                "infra/sinas/assemble.py` to regenerate.\n"
            )
            return 1
        print("sinas-package.yaml is up to date with the fragments.")
        return 0

    PACKAGE.write_text(rendered)
    print(f"wrote {PACKAGE.relative_to(HERE.parent.parent)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
