# Copyright (C) 2025 Keygraph, Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License version 3
# as published by the Free Software Foundation.
#
# Assemble the single-module pentest/report-view Sinas component from its two
# .jsx source fragments. Split out of assemble.py to keep each module under the
# 300-line cap; assemble.py imports `component_module`, `COMPONENT`, and the
# fragment paths from here.
#
# A Sinas component is ONE module. The fragments are split only so each source
# file stays small AND independently `node --check`-able as an ES module:
# report-view.parts.jsx `export`s its symbols, report-view.main.jsx `import`s
# them. When assembled into the one component module those symbols become plain
# top-level declarations sharing a single scope, so the ESM shims are stripped:
#   - the `import { ... } from "./report-view.parts.jsx"` block in main, and
#   - the leading `export ` keyword on each parts declaration,
# keeping only the lone `export default function App` the runtime entry needs.
#
# No secrets are read or written; the component bundle carries no tokens/hosts.

import pathlib

HERE = pathlib.Path(__file__).resolve().parent

# The assembled component is a GENERATED artifact (like sinas-package.yaml): it
# is written here and inlined into spec.components[0].code; --check verifies it
# is not stale against the two fragments.
COMPONENT = HERE / "components" / "report-view.jsx"
COMPONENT_PARTS = HERE / "components" / "report-view.parts.jsx"
COMPONENT_MAIN = HERE / "components" / "report-view.main.jsx"

_BANNER = (
    "// Copyright (C) 2025 Keygraph, Inc.\n"
    "//\n"
    "// This program is free software: you can redistribute it and/or modify\n"
    "// it under the terms of the GNU Affero General Public License version 3\n"
    "// as published by the Free Software Foundation.\n"
    "//\n"
    "// GENERATED by infra/sinas/assemble.py from report-view.parts.jsx +\n"
    "// report-view.main.jsx. Do NOT hand-edit; edit a fragment and re-run\n"
    "// `python3 infra/sinas/assemble.py`. This is the single-module Sinas\n"
    "// component inlined verbatim into sinas-package.yaml spec.components.\n"
)


def _strip_leading_comment(text: str) -> list[str]:
    """Drop the leading `//`/blank AGPL+doc header; keep code from there on."""
    lines = text.splitlines()
    i = 0
    while i < len(lines) and (lines[i].lstrip().startswith("//") or not lines[i].strip()):
        i += 1
    return lines[i:]


def _strip_module_shims(lines: list[str]) -> list[str]:
    """Remove the source-only ESM shims so the two fragments share one scope."""
    out: list[str] = []
    in_import = False
    for line in lines:
        if in_import:
            if line.rstrip().endswith('from "./report-view.parts.jsx";'):
                in_import = False
            continue
        if line.startswith("import {"):
            in_import = True
            continue
        if line.startswith("export ") and not line.startswith("export default"):
            line = line[len("export ") :]
        out.append(line)
    return out


def component_module() -> str:
    """Assemble report-view.jsx: parts fragment above the main shell, ESM shims
    stripped, AGPL header re-applied once at the top."""
    parts = _strip_module_shims(_strip_leading_comment(COMPONENT_PARTS.read_text()))
    main = _strip_module_shims(_strip_leading_comment(COMPONENT_MAIN.read_text()))
    body = "\n".join(parts).rstrip() + "\n\n" + "\n".join(main).rstrip() + "\n"
    return _BANNER + "\n" + body
