// SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
// Copyright (c) 2025-2026 Keygraph, Inc.
// Required Notice: Shor — https://github.com/tr4m0ryp/shor
// Noncommercial use only. Selling this software or offering it as a paid or
// hosted service requires a separate commercial license. See LICENSE & NOTICE.

/**
 * Pure CPGQL builder + parse for the guard-dominance query (spec T10, F9b, R7).
 *
 * `buildGuardDominanceScript` turns a guard/sink matcher pair into a Joern Scala
 * script run against an EXISTING CPG (task 015 built it — we reuse `cpg.bin`, we
 * do not re-parse the repo). The query is a real control-flow dominator check, the
 * exact opposite of a regex over prose: for every sensitive sink call it computes
 * `sink.dominatedBy` (the CFG nodes that dominate it on ALL paths) and partitions
 * the guard calls in the same method into those that dominate the sink and those
 * that do not. A sink with no dominating guard is reachable by a path that skips
 * authorization → CWE-862.
 *
 * 100% pure (string in / typed out) so the query shape and the structural verdict
 * are unit-testable without a Joern install.
 */

import { createHash } from "node:crypto";
import { SCRIPT_PARAMS } from "../joern/queries.js";
import type {
	GuardCandidate,
	GuardRawResult,
	GuardRawSink,
	GuardStructuralVerdict,
} from "./types.js";
import type { TaintPathStep } from "../types.js";

/** Weakness class + CWE a missing/insufficient guard implies. */
export const GUARD_VULN_CLASS = "missing_authorization";
export const GUARD_CWE = "CWE-862";

/**
 * Default authorization-check name/code matchers (framework-agnostic, broad —
 * recall over precision). Intentionally NOT a WordPress catalogue: no
 * nonce-confusion / REST-permission-gap detectors (out of scope for the general
 * engine). These are the names any web framework gives an authz gate.
 */
export const DEFAULT_GUARD_MATCHERS: readonly string[] = [
	"(?i).*(require|ensure|assert|check|verify)(Auth|Authn|Authz|Login|Session|Permission|Access|Role|Admin|Owner|User).*",
	"(?i).*(isAuthenticated|isAuthorized|isAdmin|isLoggedIn|isOwner|loggedIn).*",
	"(?i).*(hasPermission|hasRole|hasAccess|hasScope|can|cannot|authorize|authenticate).*",
	"(?i).*(canActivate|canAccess|beforeAction|before_action|guard|middleware|policy).*",
	"(?i).*(getUser|currentUser|getSession|getPrincipal)\\(\\).*",
];

/**
 * Default sensitive-sink matchers: state-changing / privileged operations that
 * MUST be authorized. Broad and general-web (writes, deletes, exec, privilege
 * mutation). The caller may override for a target's concrete data layer.
 */
export const DEFAULT_SINK_MATCHERS: readonly string[] = [
	"(?i).*(delete|remove|destroy|drop|truncate|unlink|rmdir).*",
	"(?i).*(insert|update|save|create|upsert|persist|write|set).*",
	"(?i).*(exec|execSync|spawn|system|runCommand|popen).*",
	"(?i).*(grant|revoke|setRole|assignRole|promote|demote|updatePassword|resetPassword|setPassword).*",
	"(?i).*(sendFile|writeFile|transfer|refund|charge|payout).*",
];

/** Escape a matcher into a valid Scala double-quoted string literal. */
function lit(s: string): string {
	return JSON.stringify(s);
}

/** Render a matcher list as a Scala `List("a", "b")`. */
function scalaList(items: readonly string[]): string {
	return `List(${items.map(lit).join(", ")})`;
}

/** Matchers handed to {@link buildGuardDominanceScript}. */
export interface GuardQueryMatchers {
	/** Authorization-check call matchers (defaults to {@link DEFAULT_GUARD_MATCHERS}). */
	readonly guards?: readonly string[];
	/** Sensitive-sink call matchers (defaults to {@link DEFAULT_SINK_MATCHERS}). */
	readonly sinks?: readonly string[];
}

/**
 * Build the guard-dominance Joern script. Loads the CPG, matches guard + sink
 * calls (by NAME or CODE — the same JS/TS frontend fix task 015 validated), and
 * for each sink emits its dominating vs. non-dominating guards using the CFG
 * dominator tree (`sink.dominatedBy`). Node identity is compared by `.id` because
 * dataflow/CFG traversals return fresh wrappers across Joern versions.
 */
export function buildGuardDominanceScript(matchers: GuardQueryMatchers = {}): string {
	const guards = matchers.guards ?? DEFAULT_GUARD_MATCHERS;
	const sinks = matchers.sinks ?? DEFAULT_SINK_MATCHERS;
	return [
		"// Generated by Shor services/taint/guard-dominance — Joern (Apache-2.0). Do not edit.",
		`@main def exec(${SCRIPT_PARAMS.cpg}: String, ${SCRIPT_PARAMS.out}: String): Unit = {`,
		`  importCpg(${SCRIPT_PARAMS.cpg})`,
		"  def matchCalls(pats: List[String]) =",
		"    (cpg.call.name(pats: _*) ++ cpg.call.code(pats: _*)).dedup",
		`  val guardCalls = matchCalls(${scalaList(guards)}).l`,
		`  val sinkCalls = matchCalls(${scalaList(sinks)}).l`,
		"  def nodeJson(e: io.shiftleft.codepropertygraph.generated.nodes.AstNode): ujson.Obj = {",
		"    val loc = e.location",
		'    ujson.Obj("file" -> loc.filename, "line" -> loc.lineNumber.map(_.toInt).getOrElse(-1),',
		'      "code" -> e.code, "method" -> loc.methodFullName)',
		"  }",
		"  val results = ujson.Arr()",
		"  for (sink <- sinkCalls) {",
		"    val mId = sink.method.id",
		"    val inMethod = guardCalls.filter(g => g.method.id == mId)",
		// The dominator set of the sink: nodes that lie on EVERY path to it.
		"    val domIds = sink.dominatedBy.id.toSet",
		"    val dominating = inMethod.filter(g => domIds.contains(g.id))",
		"    val nonDominating = inMethod.filter(g => !domIds.contains(g.id))",
		"    results.arr.append(ujson.Obj(",
		'      "sink" -> nodeJson(sink),',
		'      "method" -> sink.method.fullName,',
		'      "dominatingGuards" -> ujson.Arr.from(dominating.map(nodeJson)),',
		'      "nonDominatingGuards" -> ujson.Arr.from(nonDominating.map(nodeJson))))',
		"  }",
		'  val root = ujson.Obj("results" -> results)',
		`  os.write.over(os.Path(${SCRIPT_PARAMS.out}), ujson.write(root, indent = 2))`,
		"}",
	].join("\n");
}

/** Structural verdict from the two guard partitions (pure decision rule). */
export function structuralVerdict(
	dominating: readonly TaintPathStep[],
	nonDominating: readonly TaintPathStep[],
): GuardStructuralVerdict {
	if (dominating.length > 0) return "guarded";
	if (nonDominating.length > 0) return "partial_guard";
	return "unguarded";
}

/** Stable 16-hex id over the identifying fields (deterministic correlation key). */
function candidateId(method: string | undefined, sink: TaintPathStep): string {
	const key = `${method ?? ""}|${sink.file ?? ""}:${sink.line ?? ""}|${sink.code ?? ""}`;
	return createHash("sha1").update(key).digest("hex").slice(0, 16);
}

/** Normalize a raw path-step array (tolerant of a missing/garbled field). */
function steps(raw: readonly TaintPathStep[] | undefined): TaintPathStep[] {
	if (!Array.isArray(raw)) return [];
	return raw.filter((s): s is TaintPathStep => s !== null && typeof s === "object");
}

/** One raw sink entry -> a typed {@link GuardCandidate}. */
function toCandidate(raw: GuardRawSink): GuardCandidate | undefined {
	if (!raw || typeof raw !== "object" || !raw.sink) return undefined;
	const dominatingGuards = steps(raw.dominatingGuards);
	const nonDominatingGuards = steps(raw.nonDominatingGuards);
	return {
		id: candidateId(raw.method, raw.sink),
		sink: raw.sink,
		method: raw.method,
		vulnClass: GUARD_VULN_CLASS,
		cwe: GUARD_CWE,
		structuralVerdict: structuralVerdict(dominatingGuards, nonDominatingGuards),
		dominatingGuards,
		nonDominatingGuards,
	};
}

/** Deterministic parse of the dominance script's JSON into typed candidates. */
export function parseGuardResults(raw: GuardRawResult): GuardCandidate[] {
	if (!raw || !Array.isArray(raw.results)) return [];
	const out: GuardCandidate[] = [];
	for (const entry of raw.results) {
		const cand = toCandidate(entry);
		if (cand) out.push(cand);
	}
	return out;
}
