// Copyright (C) 2025 Keygraph, Inc.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License version 3
// as published by the Free Software Foundation.
//
// GENERATED by infra/sinas/assemble.py from report-view.parts.jsx +
// report-view.main.jsx. Do NOT hand-edit; edit a fragment and re-run
// `python3 infra/sinas/assemble.py`. This is the single-module Sinas
// component inlined verbatim into sinas-package.yaml spec.components.

const React = window.React;
const { useState, useMemo, useCallback } = React;

const STORES = {
  projects: "pentest/projects",
  scans: "pentest/scans",
  findings: "pentest/findings",
  reports: "pentest/reports",
};
const FUNCTIONS = {
  triggerScan: "pentest/trigger_scan",
  createProject: "pentest/create_project",
};
const SEVERITY_ORDER = ["critical", "high", "medium", "low", "info"];
const LIVE_STATUSES = ["queued", "running", "pending"];

const sdk = () => (typeof window !== "undefined" ? window.SinasSDK : undefined) || {};
const ui = () => (typeof window !== "undefined" ? window.SinasUI : undefined) || {};

// --- store reads -----------------------------------------------------------
// Prefer the props snapshot (input_data); fall back to the live proxy only if
// the runtime did not inject one. Each state is { key, value, tags?, ... }.
function readStore(inputData, storeRef) {
  const snap = inputData && (inputData[storeRef] || inputData[storeRef.split("/")[1]]);
  if (Array.isArray(snap)) return snap;
  if (snap && typeof snap === "object") {
    // Snapshot may arrive keyed by id; normalise to a {key,value} list.
    return Object.entries(snap).map(([key, value]) => ({ key, value }));
  }
  const live = sdk().stateList;
  if (typeof live === "function") {
    try {
      const res = live(storeRef);
      if (Array.isArray(res)) return res;
    } catch (_e) {
      /* proxy finicky — fall through to empty */
    }
  }
  return [];
}

// A state's payload, tolerating either {key,value} or a bare value object.
const valueOf = (s) => (s && s.value !== undefined ? s.value : s) || {};

// --- function invocation ---------------------------------------------------
// The spec confirms functions run through window.SinasSDK but does not pin the
// method name. Try the documented candidates in order; the first callable wins.
// FLAG (apply-time): confirm the real method against the via-12 runtime and
// prune the rest — do NOT add new transport here.
async function invokeFunction(ref, input) {
  const s = sdk();
  const [ns, name] = ref.split("/");
  const candidates = [
    () => s.runFunction && s.runFunction(ref, input),
    () => s.runFunction && s.runFunction(ns, name, input),
    () => s.callFunction && s.callFunction(ref, input),
    () => s.callFunction && s.callFunction(ns, name, input),
    () => s.invokeFunction && s.invokeFunction(ref, input),
    () => s.executeFunction && s.executeFunction(ref, input),
    () => s.functions && s.functions.run && s.functions.run(ref, input),
  ];
  for (const attempt of candidates) {
    const out = attempt();
    if (out !== undefined) return await out;
  }
  throw new Error(`No SinasSDK function-invoke method found for ${ref}`);
}

// --- small presentational helpers -----------------------------------------
function StatusPill({ status, progress }) {
  const s = (status || "unknown").toLowerCase();
  const live = LIVE_STATUSES.includes(s);
  const tone = s === "failed" ? "#b00020" : s === "completed" ? "#1b7f3b" : live ? "#1456b8" : "#555";
  const label = live && Number.isFinite(progress) ? `${s} ${progress}%` : s;
  return React.createElement(
    "span",
    { style: { color: "#fff", background: tone, borderRadius: 10, padding: "1px 8px", fontSize: 12 } },
    label,
  );
}

function SeverityBadge({ severity, confidence }) {
  const sev = (severity || "info").toLowerCase();
  const color =
    { critical: "#7a0012", high: "#b00020", medium: "#b8860b", low: "#2d6a4f", info: "#555" }[sev] || "#555";
  return React.createElement(
    "span",
    { style: { fontSize: 12 } },
    React.createElement("strong", { style: { color } }, sev.toUpperCase()),
    confidence ? ` · ${confidence}` : "",
  );
}

function Findings({ findings }) {
  if (!findings.length) return React.createElement("p", { style: { color: "#777" } }, "No findings recorded.");
  return React.createElement(
    "ul",
    { style: { listStyle: "none", padding: 0 } },
    findings.map((f, i) =>
      React.createElement(
        "li",
        { key: f.fingerprint || f.id || i, style: { borderTop: "1px solid #eee", padding: "6px 0" } },
        React.createElement(SeverityBadge, { severity: f.severity, confidence: f.confidence }),
        React.createElement("div", null, f.title || f.category || f.id),
        f.evidence ? React.createElement("div", { style: { color: "#666", fontSize: 13 } }, f.evidence) : null,
      ),
    ),
  );
}

function Report({ report }) {
  if (!report) return React.createElement("p", { style: { color: "#777" } }, "Report not finalized yet.");
  const counts = report.severity_counts || {};
  return React.createElement(
    "div",
    null,
    React.createElement("h3", null, report.report_title || "Security Assessment Report"),
    report.overall_risk ? React.createElement("p", null, `Overall risk: ${report.overall_risk}`) : null,
    React.createElement(
      "p",
      { style: { color: "#666", fontSize: 13 } },
      SEVERITY_ORDER.map((k) => `${k} ${counts[k] || 0}`).join(" · "),
    ),
    report.executive_summary ? React.createElement("p", null, report.executive_summary) : null,
    React.createElement(Findings, { findings: report.findings || [] }),
  );
}

function NewProjectForm({ repos, reposConnected, onCreate, busy }) {
  const [name, setName] = useState("");
  const [targetUrl, setTargetUrl] = useState("");
  const [mode, setMode] = useState("blackbox");
  const [repoRef, setRepoRef] = useState("");
  const submit = (e) => {
    e.preventDefault();
    const payload = { name, targetUrl, mode };
    if (mode === "whitebox" && repoRef) payload.repoRef = repoRef;
    onCreate(payload);
  };
  const field = (label, node) =>
    React.createElement("label", { style: { display: "block", margin: "4px 0" } }, `${label} `, node);
  return React.createElement(
    "form",
    { onSubmit: submit, style: { borderTop: "1px solid #ddd", marginTop: 12, paddingTop: 8 } },
    React.createElement("h4", null, "New project"),
    field("Name", React.createElement("input", { value: name, onChange: (e) => setName(e.target.value), required: true })),
    field(
      "Target URL",
      React.createElement("input", { value: targetUrl, onChange: (e) => setTargetUrl(e.target.value), required: true }),
    ),
    field(
      "Mode",
      React.createElement(
        "select",
        { value: mode, onChange: (e) => setMode(e.target.value) },
        React.createElement("option", { value: "blackbox" }, "blackbox"),
        reposConnected ? React.createElement("option", { value: "whitebox" }, "whitebox") : null,
      ),
    ),
    mode === "whitebox"
      ? field(
          "Repo",
          React.createElement(
            "select",
            { value: repoRef, onChange: (e) => setRepoRef(e.target.value), required: true },
            React.createElement("option", { value: "" }, "Select a repo…"),
            repos.map((r, i) =>
              React.createElement(
                "option",
                { key: i, value: r.fullName || r.full_name || r.id || r },
                r.fullName || r.full_name || r.name || String(r),
              ),
            ),
          ),
        )
      : null,
    reposConnected
      ? null
      : React.createElement(
          "p",
          { style: { color: "#777", fontSize: 12 } },
          "No GitHub repos connected — black-box only. Connect GitHub in the shor app to enable white-box.",
        ),
    React.createElement("button", { type: "submit", disabled: busy }, busy ? "Creating…" : "Create project"),
  );
}


export default function App(props) {
  const inputData = (props && props.input_data) || {};
  const [selected, setSelected] = useState(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);

  const projects = useMemo(() => readStore(inputData, STORES.projects).map(valueOf), [inputData]);
  const scans = useMemo(() => readStore(inputData, STORES.scans).map(valueOf), [inputData]);
  const findings = useMemo(() => readStore(inputData, STORES.findings).map(valueOf), [inputData]);
  const reports = useMemo(() => readStore(inputData, STORES.reports), [inputData]);
  // Repos are NOT one of the four stores: the engine exposes them live via the
  // connector's list_repos op. The runtime may surface that op result in the
  // snapshot under "pentest/repos"; absent it, the form shows black-box only.
  const repos = useMemo(() => readStore(inputData, "pentest/repos").map(valueOf), [inputData]);
  const reposConnected = repos.length > 0;

  const reportFor = useCallback(
    (scanId) => {
      const hit = reports.find((s) => s.key === scanId);
      return hit ? valueOf(hit) : undefined;
    },
    [reports],
  );
  const scansFor = useCallback(
    (projectId) =>
      scans
        .filter((s) => s.projectId === projectId)
        .sort((a, b) => String(b.updatedAt || "").localeCompare(String(a.updatedAt || ""))),
    [scans],
  );
  const findingsFor = useCallback(
    (scanId) => findings.filter((f) => f.scanId === scanId || f.scan_id === scanId),
    [findings],
  );

  const guard = useCallback(async (fn) => {
    setBusy(true);
    setError(null);
    try {
      await fn();
      if (typeof ui().refresh === "function") ui().refresh();
    } catch (e) {
      setError(e && e.message ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  }, []);

  const runScan = (projectId, ref) =>
    guard(() => invokeFunction(FUNCTIONS.triggerScan, ref ? { projectId, ref } : { projectId }));
  const createProject = (payload) => guard(() => invokeFunction(FUNCTIONS.createProject, payload));

  return React.createElement(
    "div",
    { style: { fontFamily: "system-ui, sans-serif", maxWidth: 820, margin: "0 auto", padding: 16 } },
    React.createElement("h2", null, "Shor — pentest showcase"),
    error ? React.createElement("p", { style: { color: "#b00020" } }, `Error: ${error}`) : null,
    projects.length === 0 ? React.createElement("p", { style: { color: "#777" } }, "No projects yet.") : null,
    projects.map((p) => {
      const runs = scansFor(p.projectId);
      return React.createElement(
        "section",
        { key: p.projectId, style: { border: "1px solid #e3e3e3", borderRadius: 8, padding: 12, margin: "10px 0" } },
        React.createElement(
          "div",
          { style: { display: "flex", justifyContent: "space-between", alignItems: "center" } },
          React.createElement("h3", { style: { margin: 0 } }, p.name || p.projectId),
          React.createElement("button", { disabled: busy, onClick: () => runScan(p.projectId) }, "Run / rerun"),
        ),
        React.createElement(
          "div",
          { style: { color: "#666", fontSize: 13 } },
          `${p.targetUrl || ""} · ${p.mode || "blackbox"}`,
        ),
        React.createElement(
          "ul",
          { style: { listStyle: "none", padding: 0 } },
          runs.map((r) =>
            React.createElement(
              "li",
              { key: r.scanId, style: { padding: "4px 0", cursor: "pointer" }, onClick: () => setSelected(r.scanId) },
              React.createElement(StatusPill, { status: r.status, progress: r.progress }),
              React.createElement("span", { style: { marginLeft: 8 } }, r.scanId),
              selected === r.scanId
                ? React.createElement(
                    "div",
                    { style: { marginTop: 8, paddingLeft: 8, borderLeft: "2px solid #eee" } },
                    React.createElement("h4", null, "Findings"),
                    React.createElement(Findings, { findings: findingsFor(r.scanId) }),
                    React.createElement(Report, { report: reportFor(r.scanId) }),
                  )
                : null,
            ),
          ),
        ),
      );
    }),
    React.createElement(NewProjectForm, { repos, reposConnected, onCreate: createProject, busy }),
  );
}
