// SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
// Copyright (c) 2025-2026 Keygraph, Inc.
// Required Notice: Shor — https://github.com/tr4m0ryp/shor
// Noncommercial use only. Selling this software or offering it as a paid or
// hosted service requires a separate commercial license. See LICENSE & NOTICE.

/**
 * Pure CPGQL / Joern-script builders (spec T10, R7).
 *
 * `buildTaintScript` turns a {@link TaintSpec} into a self-contained Joern Scala
 * script that the driver runs with `joern --script`. The script emits ONE JSON
 * file the driver parses deterministically. Three query families:
 *
 *   1. direct     — `sink.reachableByFlows(sources)` per vuln class.
 *   2. toStore    — `dbWrite.reachableByFlows(sources)` per store: does tainted
 *                   input reach a persistence WRITE? (first half of second-order)
 *   3. fromStore  — `sink.reachableByFlows(dbRead)` per store x vuln class: does
 *                   a value read BACK from the store reach a sink? (second half)
 *
 * The driver joins (2)+(3) on the shared store to synthesize a stored/second-
 * order flow — the through-step no engine models automatically. Sanitized paths
 * (any element matching a sanitizer regex) are dropped inside the script.
 *
 * This module is intentionally 100% pure (string in / string out) so the exact
 * query shape is unit-testable without a Joern install.
 */

import type { SinkSpec, TaintLanguage, TaintSpec } from "../types.js";

/** Joern `--language` frontend flag for a detected language (undefined => auto). */
export function joernLanguageFlag(lang: TaintLanguage): string | undefined {
	switch (lang) {
		// jssrc2cpg handles BOTH JS and TS (the one frontend, weaker than the JVM).
		case "javascript":
		case "typescript":
			return "JSSRC";
		case "java":
			return "JAVASRC";
		case "python":
			return "PYTHONSRC";
		case "go":
			return "GO";
		case "c":
			return "C";
		default:
			return undefined;
	}
}

/** Escape a matcher into a valid Scala double-quoted string literal. */
function lit(s: string): string {
	// JSON string escaping covers the backslash/quote cases Scala needs here.
	return JSON.stringify(s);
}

/** Render a matcher list as a Scala `List("a", "b")`. */
function scalaList(items: readonly string[]): string {
	return `List(${items.map(lit).join(", ")})`;
}

/** Group sink matchers by vuln class so each class is one CPG query. */
export interface SinkGroup {
	readonly vulnClass: string;
	cwe?: string | undefined;
	readonly patterns: string[];
}

export function groupSinks(sinks: readonly SinkSpec[]): SinkGroup[] {
	const byClass = new Map<string, SinkGroup>();
	for (const s of sinks) {
		const g = byClass.get(s.vulnClass);
		if (g) {
			g.patterns.push(s.name);
			if (!g.cwe && s.cwe) g.cwe = s.cwe;
		} else {
			byClass.set(s.vulnClass, {
				vulnClass: s.vulnClass,
				cwe: s.cwe,
				patterns: [s.name],
			});
		}
	}
	return [...byClass.values()];
}

/** The two `--param` keys the generated script's `@main` expects. */
export const SCRIPT_PARAMS = { cpg: "cpgFile", out: "outFile" } as const;

/**
 * Build the full Joern script for a spec. The script is version-tolerant: it
 * imports the CPG, defines sanitizer-aware flow serialization, and writes a
 * single JSON object ({language, direct[], toStore[], fromStore[]}) to `outFile`.
 */
export function buildTaintScript(spec: TaintSpec): string {
	const groups = groupSinks(spec.sinks);
	const preamble = scriptPreamble(spec);
	const direct = groups.map(directQuery).join("\n");
	const toStore = spec.throughSteps.map(toStoreQuery).join("\n");
	const fromStore = spec.throughSteps
		.map((step) => groups.map((g) => fromStoreQuery(step, g)).join("\n"))
		.join("\n");
	return [
		preamble,
		"  val direct = ujson.Arr()",
		direct,
		"  val toStore = ujson.Arr()",
		toStore,
		"  val fromStore = ujson.Arr()",
		fromStore,
		'  val root = ujson.Obj("language" -> lang, "direct" -> direct,',
		'    "toStore" -> toStore, "fromStore" -> fromStore)',
		"  os.write.over(os.Path(outFile), ujson.write(root, indent = 2))",
		"}",
	].join("\n");
}

/** Header: imports, CPG load, source list, sanitizer filter, flow serializer. */
function scriptPreamble(spec: TaintSpec): string {
	return [
		"// Generated by Shor services/taint — Joern (Apache-2.0). Do not edit.",
		`@main def exec(${SCRIPT_PARAMS.cpg}: String, ${SCRIPT_PARAMS.out}: String): Unit = {`,
		`  importCpg(${SCRIPT_PARAMS.cpg})`,
		`  val lang = ${lit(spec.language)}`,
		`  val sources = cpg.call.name(${spec.sources.map(lit).join(", ")}).l`,
		`  val sanitizers = ${scalaList(spec.sanitizers)}`,
		"  def sanitized(p: io.shiftleft.semanticcpg.language.Path): Boolean =",
		"    p.elements.exists(e => e.code != null && sanitizers.exists(s => e.code.matches(s)))",
		"  def nodeJson(e: io.shiftleft.codepropertygraph.generated.nodes.AstNode): ujson.Obj = {",
		"    val loc = e.location",
		'    ujson.Obj("file" -> loc.filename, "line" -> loc.lineNumber.map(_.toInt).getOrElse(-1),',
		'      "code" -> e.code, "method" -> loc.methodFullName)',
		"  }",
		"  def flowJson(p: io.shiftleft.semanticcpg.language.Path): ujson.Obj = {",
		"    val els = p.elements.toList",
		'    ujson.Obj("source" -> nodeJson(els.head), "sink" -> nodeJson(els.last),',
		"      \"path\" -> ujson.Arr.from(els.map(nodeJson)))",
		"  }",
		"  def flowsFor(sinkT: Iterator[io.shiftleft.codepropertygraph.generated.nodes.AstNode],",
		"      srcs: List[io.shiftleft.codepropertygraph.generated.nodes.AstNode]): ujson.Arr = {",
		"    val ps = sinkT.reachableByFlows(srcs).l.filterNot(sanitized)",
		"    ujson.Arr.from(ps.map(flowJson))",
		"  }",
	].join("\n");
}

/** One direct source->sink query for a vuln-class group. */
function directQuery(g: SinkGroup): string {
	const cwe = g.cwe ? lit(g.cwe) : "ujson.Null";
	return [
		`  { val sinkNodes = cpg.call.name(${g.patterns.map(lit).join(", ")})`,
		"    val fl = flowsFor(sinkNodes, sources)",
		"    if (fl.value.nonEmpty) direct.arr.append(",
		`      ujson.Obj("vulnClass" -> ${lit(g.vulnClass)}, "cwe" -> ${cwe}, "flows" -> fl)) }`,
	].join("\n");
}

/** First half: does tainted input reach a persistence WRITE for this store? */
function toStoreQuery(step: TaintSpec["throughSteps"][number]): string {
	return [
		`  { val writes = cpg.call.name(${step.writeMethods.map(lit).join(", ")})`,
		"    val fl = flowsFor(writes, sources)",
		"    if (fl.value.nonEmpty) toStore.arr.append(",
		`      ujson.Obj("store" -> ${lit(step.store)}, "flows" -> fl)) }`,
	].join("\n");
}

/** Second half: does a value read back from this store reach a sink class? */
function fromStoreQuery(
	step: TaintSpec["throughSteps"][number],
	g: SinkGroup,
): string {
	const cwe = g.cwe ? lit(g.cwe) : "ujson.Null";
	return [
		`  { val reads = cpg.call.name(${step.readMethods.map(lit).join(", ")}).l`,
		`    val sinkNodes = cpg.call.name(${g.patterns.map(lit).join(", ")})`,
		"    val fl = flowsFor(sinkNodes, reads)",
		"    if (fl.value.nonEmpty) fromStore.arr.append(",
		`      ujson.Obj("store" -> ${lit(step.store)}, "vulnClass" -> ${lit(g.vulnClass)},`,
		`        "cwe" -> ${cwe}, "flows" -> fl)) }`,
	].join("\n");
}
